# Build documentation

name: docs
on:
  push:
  pull_request:

jobs:
  latexuguide:
    name: LaTeX userguide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          set -ex
          sudo apt-get install -qy \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-font-utils

      - name: Build userguide
        run: |
          cd doc/latexuguide
          if ! ./makelatexdoc; then
            cat doc/latexuguide/makelatexdoc.log
            false
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: uguide.pdf
          path: doc/latexuguide/uguide.pdf
